#!/usr/bin/env bash
# Set up Apple Developer code signing + notarization for Corkscrew.
#
# Prerequisites:
#   1. Apple Developer Program membership (developer.apple.com)
#   2. "Developer ID Application" certificate created (see instructions below)
#   3. App-specific password created at appleid.apple.com
#
# This script stores credentials at ~/.corkscrew-keys/apple-signing.env
# which is sourced by build.sh and release.sh during macOS builds.

set -euo pipefail

CREDS_DIR="$HOME/.corkscrew-keys"
CREDS_FILE="$CREDS_DIR/apple-signing.env"

echo "========================================"
echo "  Corkscrew Apple Signing Setup"
echo "========================================"
echo ""

# --- Step 1: Check for Developer ID certificate ---
echo "Checking for Developer ID Application certificate..."
echo ""

IDENTITIES=$(security find-identity -v -p codesigning 2>&1)
DEV_ID=$(echo "$IDENTITIES" | grep "Developer ID Application" || true)

if [[ -z "$DEV_ID" ]]; then
  echo "ERROR: No 'Developer ID Application' certificate found."
  echo ""
  echo "To create one:"
  echo "  1. Open Xcode → Settings → Accounts"
  echo "  2. Select your Apple Developer team"
  echo "  3. Click 'Manage Certificates...'"
  echo "  4. Click '+' → 'Developer ID Application'"
  echo "  5. Wait for it to be created and installed"
  echo "  6. Run this script again"
  echo ""
  echo "Alternatively, go to https://developer.apple.com/account/resources/certificates/add"
  echo "and create a 'Developer ID Application' certificate there."
  exit 1
fi

# Extract the identity string
IDENTITY=$(echo "$DEV_ID" | head -1 | sed 's/.*"\(.*\)".*/\1/')
echo "Found: $IDENTITY"
echo ""

# --- Step 2: Get Team ID ---
TEAM_ID=$(echo "$IDENTITY" | grep -oE '\([A-Z0-9]+\)$' | tr -d '()')
if [[ -z "$TEAM_ID" ]]; then
  echo "Could not extract Team ID from certificate."
  read -r -p "Enter your Apple Team ID: " TEAM_ID
fi
echo "Team ID: $TEAM_ID"
echo ""

# --- Step 3: Get Apple ID ---
read -r -p "Enter your Apple ID (email): " APPLE_ID
echo ""

# --- Step 4: Get app-specific password ---
echo "You need an app-specific password for notarization."
echo "Create one at: https://account.apple.com/account/manage"
echo "  → Sign In & Security → App-Specific Passwords → Generate"
echo "  → Name it 'Corkscrew Notarization'"
echo ""
read -r -s -p "Enter app-specific password: " APPLE_PASSWORD
echo ""
echo ""

# --- Step 5: Write credentials file ---
mkdir -p "$CREDS_DIR"

cat > "$CREDS_FILE" <<EOF
# Apple Developer signing credentials for Corkscrew
# Generated by setup-apple-signing.sh on $(date -Iseconds)
# DO NOT commit this file to version control.

export APPLE_SIGNING_IDENTITY="$IDENTITY"
export APPLE_ID="$APPLE_ID"
export APPLE_PASSWORD="$APPLE_PASSWORD"
export APPLE_TEAM_ID="$TEAM_ID"
EOF

chmod 600 "$CREDS_FILE"
echo "Credentials saved to $CREDS_FILE (mode 0600)"
echo ""

# --- Step 6: Verify ---
echo "=== Verification ==="
echo "  Signing Identity: $IDENTITY"
echo "  Team ID:          $TEAM_ID"
echo "  Apple ID:         $APPLE_ID"
echo "  Password:         ****"
echo ""
echo "Testing codesign with this identity..."
# Create a tiny test binary to verify signing works
TEST_DIR=$(mktemp -d)
echo '#!/bin/sh' > "$TEST_DIR/test"
chmod +x "$TEST_DIR/test"
if codesign --sign "$IDENTITY" "$TEST_DIR/test" 2>&1; then
  echo "Codesign test PASSED."
else
  echo "WARNING: Codesign test failed. The certificate may not be fully set up."
  echo "Try restarting Xcode or your Mac, then run this script again."
fi
rm -rf "$TEST_DIR"

echo ""
echo "========================================"
echo "  Setup complete!"
echo "========================================"
echo ""
echo "Your next build (./scripts/build.sh or ./scripts/release.sh)"
echo "will automatically sign and notarize the app."
echo ""
echo "Users will be able to open Corkscrew directly — no terminal"
echo "commands needed."
echo ""
