//! DXVK configuration management for Linux.
//!
//! Generates and deploys `dxvk.conf` files with game-specific overrides.
//! Some DXVK settings cause issues with modded games (e.g., GraphicsPipelineLibrary).

use log::{debug, info};
use serde::{Deserialize, Serialize};
use std::collections::HashMap;
use std::path::{Path, PathBuf};

/// DXVK configuration preset.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub enum DxvkPreset {
    /// Balanced settings for most games
    Default,
    /// Maximum performance (may reduce compatibility)
    Performance,
    /// Maximum compatibility (may reduce performance)
    Compatibility,
    /// Custom user settings
    Custom,
}

/// DXVK configuration for a game.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct DxvkConfig {
    pub preset: DxvkPreset,
    pub options: HashMap<String, String>,
}

impl Default for DxvkConfig {
    fn default() -> Self {
        Self {
            preset: DxvkPreset::Default,
            options: default_options(),
        }
    }
}

/// Get default DXVK options suitable for modded games.
fn default_options() -> HashMap<String, String> {
    let mut opts = HashMap::new();
    // Disable async shader compilation (causes flickering in some games)
    opts.insert("dxvk.enableAsync".to_string(), "False".to_string());
    // HUD: off by default (users can enable via env var)
    opts.insert("dxvk.hud".to_string(), "".to_string());
    opts
}

/// Get game-specific DXVK overrides.
pub fn get_game_overrides(game_id: &str) -> HashMap<String, String> {
    let mut overrides = HashMap::new();

    match game_id {
        "skyrimse" | "skyrimspecialedition" => {
            // GraphicsPipelineLibrary causes CTDs with ENB
            overrides.insert(
                "dxvk.enableGraphicsPipelineLibrary".to_string(),
                "False".to_string(),
            );
            // Skyrim benefits from larger state cache
            overrides.insert("dxvk.numCompilerThreads".to_string(), "0".to_string());
        }
        "fallout4" => {
            overrides.insert(
                "dxvk.enableGraphicsPipelineLibrary".to_string(),
                "False".to_string(),
            );
        }
        "oblivion" | "skyrim" | "fallout3" | "falloutnv" => {
            // Older DX9 games — use d3d9 specific settings
            overrides.insert("d3d9.maxFrameLatency".to_string(), "1".to_string());
        }
        "starfield" => {
            // Starfield needs larger descriptor heap
            overrides.insert("dxvk.maxChunkSize".to_string(), "128".to_string());
        }
        _ => {}
    }

    overrides
}

/// Get preset-specific DXVK options.
fn get_preset_options(preset: &DxvkPreset) -> HashMap<String, String> {
    let mut opts = HashMap::new();

    match preset {
        DxvkPreset::Performance => {
            opts.insert("dxvk.enableAsync".to_string(), "True".to_string());
            opts.insert("dxvk.numCompilerThreads".to_string(), "0".to_string());
            opts.insert("dxvk.useRawSsbo".to_string(), "True".to_string());
        }
        DxvkPreset::Compatibility => {
            opts.insert("dxvk.enableAsync".to_string(), "False".to_string());
            opts.insert(
                "dxvk.enableGraphicsPipelineLibrary".to_string(),
                "False".to_string(),
            );
            opts.insert("dxvk.maxChunkSize".to_string(), "64".to_string());
        }
        DxvkPreset::Default | DxvkPreset::Custom => {}
    }

    opts
}

/// Generate a dxvk.conf file content for a game.
pub fn generate_config(
    game_id: &str,
    preset: &DxvkPreset,
    custom_overrides: &HashMap<String, String>,
) -> String {
    let mut lines = vec![
        "# DXVK Configuration".to_string(),
        format!("# Generated by Corkscrew for game: {}", game_id),
        format!("# Preset: {:?}", preset),
        String::new(),
    ];

    // Start with defaults
    let mut final_opts = default_options();

    // Apply preset
    for (k, v) in get_preset_options(preset) {
        final_opts.insert(k, v);
    }

    // Apply game-specific overrides
    for (k, v) in get_game_overrides(game_id) {
        final_opts.insert(k, v);
    }

    // Apply user custom overrides last (highest priority)
    for (k, v) in custom_overrides {
        final_opts.insert(k.clone(), v.clone());
    }

    // Sort keys for deterministic output
    let mut sorted: Vec<_> = final_opts.into_iter().collect();
    sorted.sort_by(|a, b| a.0.cmp(&b.0));

    for (key, value) in sorted {
        if value.is_empty() {
            lines.push(format!("# {} =", key));
        } else {
            lines.push(format!("{} = {}", key, value));
        }
    }

    lines.push(String::new());
    lines.join("\n")
}

/// Deploy dxvk.conf to a game directory.
///
/// Returns the path to the deployed config file.
pub fn deploy_config(
    game_dir: &Path,
    game_id: &str,
    preset: &DxvkPreset,
    custom_overrides: &HashMap<String, String>,
) -> Result<PathBuf, String> {
    let config_content = generate_config(game_id, preset, custom_overrides);
    let config_path = game_dir.join("dxvk.conf");

    // Check if existing config is different
    if config_path.exists() {
        if let Ok(existing) = std::fs::read_to_string(&config_path) {
            if existing == config_content {
                debug!("dxvk.conf unchanged for {}", game_id);
                return Ok(config_path);
            }
        }
    }

    std::fs::write(&config_path, &config_content)
        .map_err(|e| format!("Failed to write dxvk.conf: {}", e))?;

    info!(
        "Deployed dxvk.conf to {} (preset: {:?})",
        game_dir.display(),
        preset
    );
    Ok(config_path)
}

/// Detect DXVK version installed in a Wine prefix.
pub fn detect_dxvk_version(prefix_path: &Path) -> Option<String> {
    // Case-insensitive lookup for system32 (Wine may use any casing)
    let system32_candidates = [
        prefix_path.join("drive_c/windows/system32"),
        prefix_path.join("drive_c/Windows/System32"),
        prefix_path.join("drive_c/windows/System32"),
    ];
    let system32 = system32_candidates.iter().find(|p| p.is_dir())?;

    let dxvk_dll = system32.join("d3d11.dll");
    if !dxvk_dll.exists() {
        return None;
    }

    let metadata = std::fs::metadata(&dxvk_dll).ok()?;
    let size = metadata.len();

    // DXVK DLLs are typically 1-5MB. Wine builtin d3d11.dll is smaller.
    if size > 500_000 {
        // Search for version string in the first 64KB of the binary
        // (version info is near the start, avoids reading multi-MB DLLs fully)
        let mut buf = vec![0u8; (size as usize).min(65536)];
        use std::io::Read;
        if let Ok(mut f) = std::fs::File::open(&dxvk_dll) {
            let _ = f.read(&mut buf);
        }
        let data_str = String::from_utf8_lossy(&buf);
        for pattern in &["DXVK v", "dxvk-"] {
            if let Some(idx) = data_str.find(pattern) {
                let start = idx + pattern.len();
                let end = data_str[start..]
                    .find(|c: char| !c.is_ascii_digit() && c != '.')
                    .map(|p| p + start)
                    .unwrap_or(start);
                let version = &data_str[start..end.min(start + 20)];
                if !version.is_empty() {
                    return Some(version.to_string());
                }
            }
        }
        Some("unknown".to_string())
    } else {
        None // Likely Wine builtin
    }
}

// ---------------------------------------------------------------------------
// Tests
// ---------------------------------------------------------------------------

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_default_config() {
        let config = generate_config("skyrimse", &DxvkPreset::Default, &HashMap::new());
        assert!(config.contains("dxvk.enableGraphicsPipelineLibrary = False"));
        assert!(config.contains("Generated by Corkscrew"));
    }

    #[test]
    fn test_performance_preset() {
        let config = generate_config("skyrimse", &DxvkPreset::Performance, &HashMap::new());
        assert!(config.contains("dxvk.enableAsync = True"));
    }

    #[test]
    fn test_compatibility_preset() {
        let config = generate_config("skyrimse", &DxvkPreset::Compatibility, &HashMap::new());
        assert!(config.contains("dxvk.enableGraphicsPipelineLibrary = False"));
        assert!(config.contains("dxvk.enableAsync = False"));
    }

    #[test]
    fn test_custom_overrides() {
        let mut custom = HashMap::new();
        custom.insert("dxvk.enableAsync".to_string(), "True".to_string());
        let config = generate_config("skyrimse", &DxvkPreset::Default, &custom);
        // Custom override should win
        assert!(config.contains("dxvk.enableAsync = True"));
    }

    #[test]
    fn test_game_specific_overrides() {
        let overrides = get_game_overrides("skyrimse");
        assert!(overrides.contains_key("dxvk.enableGraphicsPipelineLibrary"));
    }

    #[test]
    fn test_deploy_config() {
        let dir = tempfile::tempdir().unwrap();
        let result = deploy_config(
            dir.path(),
            "skyrimse",
            &DxvkPreset::Default,
            &HashMap::new(),
        );
        assert!(result.is_ok());
        let path = result.unwrap();
        assert!(path.exists());
        let content = std::fs::read_to_string(&path).unwrap();
        assert!(content.contains("dxvk.enableGraphicsPipelineLibrary = False"));
    }

    #[test]
    fn test_deploy_config_idempotent() {
        let dir = tempfile::tempdir().unwrap();
        let path1 = deploy_config(
            dir.path(),
            "skyrimse",
            &DxvkPreset::Default,
            &HashMap::new(),
        )
        .unwrap();
        let mtime1 = std::fs::metadata(&path1).unwrap().modified().unwrap();

        // Small sleep to ensure mtime would differ if file were rewritten
        std::thread::sleep(std::time::Duration::from_millis(50));

        let path2 = deploy_config(
            dir.path(),
            "skyrimse",
            &DxvkPreset::Default,
            &HashMap::new(),
        )
        .unwrap();
        let mtime2 = std::fs::metadata(&path2).unwrap().modified().unwrap();

        // File should NOT have been rewritten (same content)
        assert_eq!(mtime1, mtime2);
    }

    #[test]
    fn test_unknown_game_no_crash() {
        let config = generate_config("unknown_game", &DxvkPreset::Default, &HashMap::new());
        assert!(config.contains("Generated by Corkscrew"));
    }

    #[test]
    fn test_detect_dxvk_version_missing_dll() {
        let dir = tempfile::tempdir().unwrap();
        assert!(detect_dxvk_version(dir.path()).is_none());
    }

    #[test]
    fn test_dx9_game_overrides() {
        let overrides = get_game_overrides("oblivion");
        assert!(overrides.contains_key("d3d9.maxFrameLatency"));
        assert_eq!(overrides.get("d3d9.maxFrameLatency").unwrap(), "1");
    }

    #[test]
    fn test_starfield_overrides() {
        let overrides = get_game_overrides("starfield");
        assert!(overrides.contains_key("dxvk.maxChunkSize"));
    }

    #[test]
    fn test_empty_hud_commented() {
        let config = generate_config("skyrimse", &DxvkPreset::Default, &HashMap::new());
        // Empty values should be commented out
        assert!(config.contains("# dxvk.hud ="));
    }

    #[test]
    fn test_config_deterministic() {
        let c1 = generate_config("skyrimse", &DxvkPreset::Default, &HashMap::new());
        let c2 = generate_config("skyrimse", &DxvkPreset::Default, &HashMap::new());
        assert_eq!(c1, c2);
    }
}
